/* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, you can obtain one at
 * https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2025 Lander Gallastegi (LNDF)
 */

#include "../sce.h"

PSPCSDK_STUB(sceVoiceChatInitialize)
PSPCSDK_STUB(sceVoiceChatTerminate)
PSPCSDK_STUB(sceVoiceChatRequestRegisterSession)
PSPCSDK_STUB(sceVoiceChatRequestUnregisterSession)
PSPCSDK_STUB(sceVoiceChatRegisterHandlers)
PSPCSDK_STUB(sceVoiceChatRegisterMicEventHandler)
PSPCSDK_STUB(sceVoiceChatUnregisterMicEventHandler)
PSPCSDK_STUB(sceVoiceChatProcessEvent)
PSPCSDK_STUB(sceVoiceChatCreateRequest)
PSPCSDK_STUB(sceVoiceChatDeleteRequest)
PSPCSDK_STUB(sceVoiceChatAbortRequest)
PSPCSDK_STUB(sceVoiceChatRequestCreatePlayerSessionVoiceChatChannel)
PSPCSDK_STUB(sceVoiceChatRequestDeletePlayerSessionVoiceChatChannel)
PSPCSDK_STUB(sceVoiceChatRequestJoinPlayerSessionVoiceChatChannel)
PSPCSDK_STUB(sceVoiceChatRequestLeavePlayerSessionVoiceChatChannel)
PSPCSDK_STUB(sceVoiceChatRequestUpdatePlayerSessionVoiceChatChannelName)
PSPCSDK_STUB(sceVoiceChatRequestCreateGameSessionVoiceChatChannel)
PSPCSDK_STUB(sceVoiceChatRequestDeleteGameSessionVoiceChatChannel)
PSPCSDK_STUB(sceVoiceChatRequestJoinGameSessionVoiceChatChannel)
PSPCSDK_STUB(sceVoiceChatRequestLeaveGameSessionVoiceChatChannel)
PSPCSDK_STUB(sceVoiceChatRequestUpdateGameSessionVoiceChatChannelName)
PSPCSDK_STUB(sceVoiceChatRequestCreateVoiceChatGroup)
PSPCSDK_STUB(sceVoiceChatRequestDeleteVoiceChatGroup)
PSPCSDK_STUB(sceVoiceChatRequestJoinVoiceChatGroup)
PSPCSDK_STUB(sceVoiceChatRequestLeaveVoiceChatGroup)
PSPCSDK_STUB(sceVoiceChatGetChatChannelMemberInfoList)
PSPCSDK_STUB(sceVoiceChatGetChatGroupMemberInfoList)
PSPCSDK_STUB(sceVoiceChatGetChannelMemberActiveChannelMatchingState)
PSPCSDK_STUB(sceVoiceChatGetChannelMemberVoiceConnectionState)
PSPCSDK_STUB(sceVoiceChatGetMicState)
PSPCSDK_STUB(sceVoiceChatRequestSetChannelMute)
PSPCSDK_STUB(sceVoiceChatRequestSetMemberMute)
PSPCSDK_STUB(sceVoiceChatRequestSetMemberVolume)
PSPCSDK_STUB(sceVoiceChatRegisterMicEventHandler2)
PSPCSDK_STUB(sceVoiceChatUnregisterMicEventHandler2)
PSPCSDK_STUB(sceVoiceChatGetActiveChannel)
PSPCSDK_STUB(sceVoiceChatRequestSetActiveChannel)
PSPCSDK_STUB(sceVoiceChatRequestSetMicMute)
PSPCSDK_STUB(sceVoiceChatRequestSetMicVolume)
PSPCSDK_STUB(sceVoiceChatGetActiveDeviceInfo)
PSPCSDK_STUB(sceVoiceChatRegisterDeviceEventHandler)
PSPCSDK_STUB(sceVoiceChatUnregisterDeviceEventHandler)
